### ISSUE TITLE
Permission denied (python)

### ISSUE THREAD

**Issue by muffincode** [seomoz/SEOmozAPISamples#43]
Running the example in python with newly generated credentials gives me this :/ Not sure what to understand from that. 

I see "Permission denied" — but I'm not sure what more to do

```
 laurentfite@cest-pas-moi  ~/workspace/moz-domainauthority/SEOmozAPISamples/python   master ● ?  python3 example.py                                   1 ↵  5880  16:09:42
Traceback (most recent call last):
  File "/Users/laurentfite/workspace/moz-domainauthority/SEOmozAPISamples/python/mozscape.py", line 338, in query
    return json.load(reader(urlopen(request, data)))
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Permission denied: pcklmkkmopjgphjdpcigohkbmmkfmkljniklmd

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 16, in <module>
    metrics = client.urlMetrics(['www.moz.com', 'www.moz.com/blog'])
  File "/Users/laurentfite/workspace/moz-domainauthority/SEOmozAPISamples/python/mozscape.py", line 360, in urlMetrics
    Cols=cols)
  File "/Users/laurentfite/workspace/moz-domainauthority/SEOmozAPISamples/python/mozscape.py", line 342, in query
    raise MozscapeError(e.read())
mozscape.MozscapeError: b'{\n        "status" : "401",\n        "error_message" : "Permission denied: pcklmkkmopjgphjdpcigohkbmmkfmkljniklmd"\n      }'
```

**Comment by jda5** [comment]
Same issue.
